### ISSUE TITLE
Pull Fast Forward

### ISSUE THREAD

**Issue by rthomson83** [gmasterscm/ama#6]
Is there any pull fast forward option? It just seems to pull origin and doesn't attempt to move along the local.

**Comment by rubarax** [comment]
Do you mean that after running an pull operation (origin/task), the local reference (task) is not updated? That is weird, since updating the local reference is the default behavior.

Pull will always try to update the local reference. Fetch will not do it.

If you mean that you cannot configure the '--no-ff' or '--ff-only' options for the pull operation, you are right. There is not a way to customize the pull operation right now.

**Comment by rthomson83** [comment]
I think I'm just trying to use this tool like another git client I use. Even if you are not on the branch you can pull it and it will ff.
GM tries to pull the unchecked out branch into the current branch. Not saying this is wrong or anything, still trying to get my head around the functionaly. ;-)
